# Binaries
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'fd'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go'
brew 'grep'
brew 'htop'
brew 'jq'
brew 'k9s'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'kustomize'
brew 'mas'
brew 'nvm'
brew 'ripgrep'
brew 'semgrep'
brew 'starship'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Apps
cask '1password'
cask 'bartender'
cask 'iterm2'
cask 'ghostty'
cask 'google-chrome'
cask 'raycast'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'todoist'
cask 'visual-studio-code'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'

# Mac App Store
# mas 'Xcode', id: 497799835
