# Binaries — system-level tools not managed by mise
brew 'bash'
brew 'ca-certificates'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gpg'
brew 'graphviz'
brew 'grep'
brew 'harlequin'
brew 'htop'
brew 'mas'
brew 'powerlevel10k'
brew 'tree'
brew 'tw93/tap/mole'
brew 'vim'
brew 'watch'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Apps
cask '1password'
cask 'claude-code@latest'
cask 'discord'
cask 'ghostty'
cask 'google-chrome'
cask 'jordanbaird-ice'
cask 'linear-linear'
cask 'nvidia-geforce-now'
cask 'obsidian'
cask 'orbstack'
cask 'rapidapi'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'todoist-app'
cask 'visual-studio-code'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'

# Mac App Store
# mas 'Xcode', id: 497799835
