name: Build Devbox Image

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVBOX_IMAGE_NAME: rcrowe-dotfiles
      DEVBOX_IMAGE_SITES: zrh
    steps:
      - uses: actions/checkout@v4

      - name: Configure access to Namespace
        uses: namespacelabs/nscloud-setup@v0

      - name: Install Devbox CLI
        run: curl -fsSL get.namespace.so/devbox/install.sh | bash

      - name: Build Devbox image
        run: devbox image build --optimize=false --name=${{ env.DEVBOX_IMAGE_NAME }} -f .devbox/Dockerfile .

      - name: Optimise for specific sites
        run: devbox image optimize --name=${{ env.DEVBOX_IMAGE_NAME }} --site=${{ env.DEVBOX_IMAGE_SITES }}
