name: Build Devbox Image

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - name: Install Devbox CLI
        run: curl -fsSL get.namespace.so/devbox/install.sh | bash

      - name: Build Devbox image
        run: devbox image build . --name=rcrowe-dotfiles -f .devbox/Dockerfile
